import { MetadataRoute } from "next";
import { client } from "@/sanity/client";
import { SITEMAP_QUERY } from "../../sanity/lib/queries";

type ChangeFrequency =
  | "always"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly"
  | "never";
  
export const revalidate = 0;

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  try {
    const paths =
      await client.fetch<{ href: string; _updatedAt: string }[]>(SITEMAP_QUERY);

    const baseUrl =
      process.env.VERCEL && process.env.VERCEL_ENV === "production"
        ? "https://foreignembassyattestation.com/"
        : process.env.VERCEL_URL
          ? `https://${process.env.VERCEL_URL}`
          : "http://localhost:3000";

    const dynamicPaths: MetadataRoute.Sitemap = paths.map((path) => ({
      url: new URL(path.href, baseUrl).toString(),
      lastModified: new Date(path._updatedAt),
      changeFrequency: "weekly" as ChangeFrequency,
      priority: 1,
    }));

    const staticUrls = [
      "/",
      "/attestation-services-in-bangalore",
      "/degree-certificate-attestation-in-bangalore",
      "/apostille-services-in-bangalore",
      "/degree-certificate-apostille-in-bangalore",
      "/state-hrd-attestation-in-bangalore",
      "/karnataka-state-hrd-attestation-in-bangalore",
      "/tamil-nadu-state-hrd-attestation-in-bangalore",
      "/kerala-state-hrd-attestation-in-bangalore",
      "/andhra-pradesh-state-hrd-attestation-in-bangalore",
      "/maharashtra-state-hrd-attestation-in-bangalore",
      "/telangana-state-hrd-attestation-in-bangalore",
      "/mofa-attestation-in-bangalore",
      "/pcc-verification-in-bangalore",
      "/oman-pcc-verification-in-bangalore",
      "/kuwait-pcc-verification-in-bangalore",
      "/saudi-arabia-pcc-verification-in-bangalore",
      "/qatar-pcc-verification-in-bangalore",
      "/uae-pcc-verification-in-bangalore",
      "/mea-apostille-services-in-bangalore",
      "/wes-verification-attestation-in-bangalore",
      "/visa-stamping-services-in-bangalore",
      "/contact-us",
      "/blog",
      "/uae-embassy-attestation-in-bangalore",
      "/qatar-embassy-attestation-in-bangalore",
      "/kuwait-embassy-attestation-in-bangalore",
      "/bahrain-embassy-attestation-in-bangalore",
      "/saudi-arabia-embassy-attestation-in-bangalore",
      "/birth-certificate-attestation-in-bangalore",
      "/marriage-certificate-attestation-in-bangalore",
      "/commercial-certificate-attestation-in-bangalore",
      "/salary-certificate-attestation-in-bangalore",
      "/equivalence-certificate-attestation-in-bangalore",
      "/single-status-certificate-attestation-in-bangalore",
      "/ministry-of-education-department-attestation-in-bangalore",
      "/foreign-affairs-attestation-in-bangalore",
      "/transfer-certificate-attestation-in-bangalore",
      "/medical-certificate-attestation-in-bangalore",
      "/ministry-of-health-department-attestation-in-bangalore",
      "/ministry-of-justice-attestation-in-bangalore",
      "/china-embassy-attestation-in-bangalore",
      "/vietnam-embassy-attestation-in-bangalore",
      "/taiwan-embassy-attestation-in-bangalore",
      "/egypt-embassy-attestation-in-bangalore",
      "/nigeria-embassy-attestation-in-bangalore",
      "/malaysia-embassy-attestation-in-bangalore",
      "/philippines-embassy-attestation-in-bangalore",
      "/oman-apostille-services-in-bangalore",
      "/italy-apostille-services-in-bangalore",
      "/germany-apostille-services-in-bangalore",
      "/australia-apostille-services-in-bangalore",
      "/austria-apostille-services-in-bangalore",
      "/france-apostille-services-in-bangalore",
      "/lithuania-apostille-services-in-bangalore",
      "/mexico-apostille-services-in-bangalore",
      "/netherlands-apostille-services-in-bangalore",
      "/uk-apostille-services-in-bangalore",
      "/usa-apostille-services-in-bangalore",
      "/marriage-certificate-apostille-in-bangalore",
      "/commercial-documents-apostille-in-bangalore",
      "/birth-certificate-apostille-in-bangalore",
      "/uae-embassy-attestation-for-degree-certificates-in-bangalore",
      "/uae-embassy-office-in-new-delhi",
      "/attestation-services-in-belagavi",
      "/attestation-services-in-bellary",
      "/attestation-services-in-davangere",
      "/attestation-services-in-hubballi",
      "/attestation-services-in-mangalore",
      "/attestation-services-in-mysore",
      "/attestation-services-in-shivamogga",
      "/bahrain-embassy-office-in-new-delhi",
      "/kuwait-embassy-office-in-new-delhi",
      "/qatar-embassy-office-in-new-delhi",
      "/saudi-arabia-embassy-office-in-new-delhi",
      "/uae-embassy-office-in-new-delhi",
      "/attestation-services-in-bommanahalli",
      "/attestation-services-in-bannerghatta-road",
      "/attestation-services-in-kalyan-nagar",
      "/attestation-services-in-magadi-road",
      "/attestation-services-in-whitefield",
      "/attestation-services-in-mg-road",
      "/attestation-services-in-jp-nagar",
      "/attestation-services-in-bommasandra",
      "/attestation-services-in-mahadevapura",
      "/attestation-services-in-yelahanka",
      "/attestation-services-in-kanakanagar",
      "/attestation-services-in-dooravani-nagar",
      "/attestation-services-in-devarajeevanahalli",
      "/attestation-services-in-kothnur",
      "/attestation-services-in-vijayanagar",
      "/attestation-services-in-agara",
      "/attestation-services-in-hsr-layout",
      "/attestation-services-in-ulsoor",
      "/attestation-services-in-jayanagar",
      "/attestation-services-in-btm-layout",
      "/attestation-services-in-hebbal",
      "/attestation-services-in-banashankari",
      "/attestation-services-in-bellandur",
      "/attestation-services-in-varthur",
      "/attestation-services-in-devanahalli",
      "/attestation-services-in-bagalur",
      "/attestation-services-in-basaveshwara-nagar",
      "/attestation-services-in-fraser-town",
      "/attestation-services-in-vivek-nagar",
      "/attestation-services-in-laggere",
      "/attestation-services-in-kr-puram",
      "/attestation-services-in-rr-nagar",
      "/attestation-services-in-kodihalli",
      "/attestation-services-in-jeevabhimanaga",
      "/attestation-services-in-vidyaranyapura",
      "/attestation-services-in-yeshwanthapura",
      "/attestation-services-in-rmv-extension",
      "/attestation-services-in-kadugodi",
      "/attestation-services-in-nagarbhavi",
      "/attestation-services-in-indiranagar",
      "/attestation-services-in-chikkabanavara",
      "/attestation-services-in-mathikere",
      "/attestation-services-in-maruthi-sevanagar",
      "/attestation-services-in-vasanthpura",
      "/attestation-services-in-konankunte",
      "/attestation-services-in-dharwad",
      "/attestation-services-in-hoskote",
      "/attestation-services-in-jigani",
      "/attestation-services-in-manipal",
      "/attestation-services-in-raichur",
      "/attestation-services-in-ullal",
      "/attestation-services-in-udupi",
      "/attestation-services-in-kalaburagi",
      "/attestation-services-in-anekal",
      "/attestation-services-in-bhatkal",
      "/attestation-services-in-vijayapura",
      "/attestation-services-in-hassan",
      "/attestation-services-in-kolar",
      "/attestation-services-in-chikkamagaluru",
      "/attestation-services-in-hosapete",
      "/attestation-services-in-channapatna",
      "/attestation-services-in-bidar",
      "/attestation-services-in-karwar",
      "/attestation-services-in-mandya",
      "/attestation-services-in-bramavara",
      "/attestation-services-in-kundapura",
      "/attestation-services-in-bhadravathi",
      "/attestation-services-in-sirsi",
      "/degree-certificate-attestation-for-saudi-arabia",
      "/degree-certificate-attestation-for-uae",
      "/degree-certificate-attestation-for-qatar",
      "/degree-certificate-attestation-for-bahrain",
      "/degree-certificate-attestation-for-kuwait",
      "/degree-certificate-apostille-for-oman",
      "/degree-certificate-apostille-for-australia",
      "/degree-certificate-apostille-for-france",
      "/degree-certificate-apostille-for-lithuania",
      "/attestation-fees-in-bangalore",
      "/apostille-fees-in-bangalore",
      "/certificate-attestation-cost-in-bangalore",
      "/certificate-apostille-cost-in-bangalore",
      "/uae-embassy-attestation-for-degree-certificates-in-bangalore",
      "/uae-embassy-attestation-for-birth-certificates-in-bangalore",
      "/uae-embassy-attestation-for-marriage-certificates-in-bangalore",
      "/uae-embassy-attestation-for-commercial-documents-in-bangalore",
      "/other-services"
    ].map((path) => ({
      url: new URL(path, baseUrl).toString(),
      lastModified: new Date(),
      changeFrequency: "weekly" as ChangeFrequency,
      priority: 0.8,
    }));

    return [...dynamicPaths, ...staticUrls];
  } catch (error) {
    console.error("Failed to generate sitemap:", error);
    return [];
  }
}
